package olp.hutechfoss.provideservice.error;


public enum ErrorCode {
    SYSTEM_ERROR("G10001"),
    DATA_NOT_FOUND("G10005"),
    LOGIN_ALREADY_USED("LOGIN_ALREADY_USED"),
    EMAIL_ALREADY_USED("EMAIL_ALREADY_USED"),
    USER_EXIST("USER_EXIST"),
    AUTHORITY_EXISTS("AUTHORITY_EXISTS"),  // Thêm mã lỗi cho authority
    INVALID_ID("ID_INVALID"),
    FIELD_INVALID("FIELD_INVALID"),
    INVALID_PASSWORD("INVALID_PASSWORD"),
    INVALID_FIELD("FIELD_INVALID"),
    REQUIRED_FIELD_MISSING("LACK_REQUIRED_FIELD"),
    OBJECT_OPTIONAL_NULL("OBJECT_OPTIONAL_NULL"),
    FILE_IS_LAGGER("FILE_IS_LAGGER"),
    OBJECT_IS_EXIST("OBJECT_IS_EXIST"),
    GRADE_EXISTED("GRADE_EXISTED"),
    GRADE_ID_NULL("GRADE_ID_NULL"),
    GRADE_NOT_FOUND("GRADE_NOT_FOUND"),
    TOPIC_ID_NULL("TOPIC_ID_NULL"),
    TOPIC_EXISTED("TOPIC_EXISTERD"),;

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
