package hutechfoss.vrelief.admin.domain;

import static hutechfoss.vrelief.admin.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ChiTietDieuPhoiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChiTietDieuPhoiAllPropertiesEquals(ChiTietDieuPhoi expected, ChiTietDieuPhoi actual) {
        assertChiTietDieuPhoiAutoGeneratedPropertiesEquals(expected, actual);
        assertChiTietDieuPhoiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChiTietDieuPhoiAllUpdatablePropertiesEquals(ChiTietDieuPhoi expected, ChiTietDieuPhoi actual) {
        assertChiTietDieuPhoiUpdatableFieldsEquals(expected, actual);
        assertChiTietDieuPhoiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChiTietDieuPhoiAutoGeneratedPropertiesEquals(ChiTietDieuPhoi expected, ChiTietDieuPhoi actual) {
        assertThat(expected)
            .as("Verify ChiTietDieuPhoi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChiTietDieuPhoiUpdatableFieldsEquals(ChiTietDieuPhoi expected, ChiTietDieuPhoi actual) {
        assertThat(expected)
            .as("Verify ChiTietDieuPhoi relevant properties")
            .satisfies(e -> assertThat(e.getPhieuDieuPhoiId()).as("check phieuDieuPhoiId").isEqualTo(actual.getPhieuDieuPhoiId()))
            .satisfies(e -> assertThat(e.getNhuYeuPhamId()).as("check nhuYeuPhamId").isEqualTo(actual.getNhuYeuPhamId()))
            .satisfies(e -> assertThat(e.getSoLuong()).as("check soLuong").isEqualTo(actual.getSoLuong()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e ->
                assertThat(e.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChiTietDieuPhoiUpdatableRelationshipsEquals(ChiTietDieuPhoi expected, ChiTietDieuPhoi actual) {
        // empty method
    }
}
