package hutechfoss.vrelief.admin.domain;

import static hutechfoss.vrelief.admin.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class LoaiNhuYeuPhamAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiNhuYeuPhamAllPropertiesEquals(LoaiNhuYeuPham expected, LoaiNhuYeuPham actual) {
        assertLoaiNhuYeuPhamAutoGeneratedPropertiesEquals(expected, actual);
        assertLoaiNhuYeuPhamAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiNhuYeuPhamAllUpdatablePropertiesEquals(LoaiNhuYeuPham expected, LoaiNhuYeuPham actual) {
        assertLoaiNhuYeuPhamUpdatableFieldsEquals(expected, actual);
        assertLoaiNhuYeuPhamUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiNhuYeuPhamAutoGeneratedPropertiesEquals(LoaiNhuYeuPham expected, LoaiNhuYeuPham actual) {
        assertThat(expected)
            .as("Verify LoaiNhuYeuPham auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiNhuYeuPhamUpdatableFieldsEquals(LoaiNhuYeuPham expected, LoaiNhuYeuPham actual) {
        assertThat(expected)
            .as("Verify LoaiNhuYeuPham relevant properties")
            .satisfies(e -> assertThat(e.getTenLoai()).as("check tenLoai").isEqualTo(actual.getTenLoai()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e ->
                assertThat(e.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiNhuYeuPhamUpdatableRelationshipsEquals(LoaiNhuYeuPham expected, LoaiNhuYeuPham actual) {
        // empty method
    }
}
