package hutechfoss.vrelief.admin.domain;

import static hutechfoss.vrelief.admin.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class NhaCungCapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhaCungCapAllPropertiesEquals(NhaCungCap expected, NhaCungCap actual) {
        assertNhaCungCapAutoGeneratedPropertiesEquals(expected, actual);
        assertNhaCungCapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhaCungCapAllUpdatablePropertiesEquals(NhaCungCap expected, NhaCungCap actual) {
        assertNhaCungCapUpdatableFieldsEquals(expected, actual);
        assertNhaCungCapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhaCungCapAutoGeneratedPropertiesEquals(NhaCungCap expected, NhaCungCap actual) {
        assertThat(expected)
            .as("Verify NhaCungCap auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhaCungCapUpdatableFieldsEquals(NhaCungCap expected, NhaCungCap actual) {
        assertThat(expected)
            .as("Verify NhaCungCap relevant properties")
            .satisfies(e -> assertThat(e.getTenNhaCungCap()).as("check tenNhaCungCap").isEqualTo(actual.getTenNhaCungCap()))
            .satisfies(e -> assertThat(e.getSoDienThoai()).as("check soDienThoai").isEqualTo(actual.getSoDienThoai()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getDiaChi()).as("check diaChi").isEqualTo(actual.getDiaChi()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e ->
                assertThat(e.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhaCungCapUpdatableRelationshipsEquals(NhaCungCap expected, NhaCungCap actual) {
        // empty method
    }
}
